Warning: Traceback of forward call that caused the error:
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/__main__.py", line 39, in <module>
    main()
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/__main__.py", line 36, in main
    usecase=args.usecase, prefix=args.prefix, omp=args.omp)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/app.py", line 143, in run
    train_fn(EPOCHS, auxweight, model, trainloader, testloader, criterion, optimizer, LRDROPS, LRFACTOR, TAG, usecase, loadmodel=loadmodel)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/app.py", line 181, in train_epochs_iterative
    avg_train_loss, grads, mags = train_epoch_iterative(model, auxweight, trainloader, criterion, optimizer, usecase)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/app.py", line 211, in train_epoch_iterative
    for logits, preds, layer_aux_loss in model(x):
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/models.py", line 421, in forward
    x, layer_aux_loss = layer(x)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/models.py", line 607, in forward
    aux_loss = self.mse(self.embiggen(aux_in.detach(), aux).detach(), aux)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 431, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/site-packages/torch/nn/functional.py", line 2211, in mse_loss
    ret = (input - target) ** 2
 (print_stack at /opt/conda/conda-bld/pytorch_1579022060824/work/torch/csrc/autograd/python_anomaly_mode.cpp:57)
Traceback (most recent call last):
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/__main__.py", line 39, in <module>
    main()
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/__main__.py", line 36, in main
    usecase=args.usecase, prefix=args.prefix, omp=args.omp)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/app.py", line 143, in run
    train_fn(EPOCHS, auxweight, model, trainloader, testloader, criterion, optimizer, LRDROPS, LRFACTOR, TAG, usecase, loadmodel=loadmodel)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/app.py", line 181, in train_epochs_iterative
    avg_train_loss, grads, mags = train_epoch_iterative(model, auxweight, trainloader, criterion, optimizer, usecase)
  File "/home-nfs/lorell/new_12s/SparseDebugging/src/app.py", line 214, in train_epoch_iterative
    loss.backward(retain_graph=True)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home-nfs/lorell/miniconda3/envs/baby/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function 'PowBackward0' returned nan values in its 0th output.
